FROM armdocker.rnd.ericsson.se/proj-adp-cicd-drop/bob-asciidocbuilder
# Patching builder with a new version until the adp one gets updated
RUN wget -O /notagtool/asciidoc-8.6.9/etc/asciidoc/filters/plantuml/plantuml.jar \
    https://arm.seli.gic.ericsson.se/artifactory/jcenter-2rc-cache/net/sourceforge/plantuml/plantuml/1.2021.5/plantuml-1.2021.5.jar